<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Sqm.Migrator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Client" Version="7.14.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

</Project>
